name: Build, Deploy, and Verify Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-deploy-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push proxyApi image
        run: |
          docker build -f docker/Dockerfile.proxyApi -t ayush272002/exchange:proxyApi .
          docker push ayush272002/exchange:proxyApi

      - name: Verify worker image by pulling
        run: |
          docker pull ayush272002/exchange:proxyApi
          docker images | grep ayush272002/exchange:proxyApi